# Generated by Django 5.0 on 2024-01-14 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('carga_horaria', models.IntegerField(max_length=4)),
                ('investimento', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
