# Generated by Django 5.0 on 2024-01-15 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0002_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='carga_horaria',
            field=models.IntegerField(),
        ),
    ]
